name: Dev build and checks

on:
  push:
    branches: [dev]

permissions:
  id-token: write
  contents: read

jobs:
  checks:
    name: Linter Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Python Black
        uses: psf/black@stable
        with:
          src: ./ldeep
          options: --check --diff
