name: Python Unit Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Python Black
        uses: psf/black@stable
        with:
          src: ./ldeep
          options: --check --diff

      - name: Set up PDM
        run: python3.12 -m pip install pdm

      - name: Install dependencies
        run: pdm install
